productos = [
  {
    nombre: "palo celeste",
    categoria: "palos",
    precio: "$100000",
    id: 1,
    image: "https://via.placeholder.com/100",
  },
  {
    nombre: "palo negro",
    categoria: "palos",
    precio: "$200000",
    id: 2,
    image: `img/funda_rosa.webp`,
  },
  {
    nombre: "palo de madera",
    categoria: "palos",
    precio: "$220000",
    id: 3,
    image: "https://via.placeholder.com/100",
  },
  {
    nombre: "palo vlack",
    categoria: "palos",
    precio: "$190000",
    id: 4,
    image: "https://via.placeholder.com/100",
  },
  {
    nombre: "palo jr",
    categoria: "palos",
    precio: "$150000",
    id: 5,
    image: "https://via.placeholder.com/100",
  },
  {
    nombre: "bolso negro",
    categoria: "bolsos",
    precio: "$90000",
    id: 6,
    image: "https://via.placeholder.com/100",
  },
  {
    nombre: "funda",
    categoria: "bolsos",
    precio: "$40000",
    id: 7,
    image: "https://via.placeholder.com/100",
  },
  {
    nombre: "bocha colores",
    categoria: "accesorios",
    precio: "$3000",
    id: 8,
    image: "https://via.placeholder.com/100",
  },
  {
    nombre: "bocha blanca",
    categoria: "accesorios",
    precio: "$3100",
    id: 9,
    image: "https://via.placeholder.com/100",
  },
  {
    nombre: "bocha profesional",
    categoria: "accesorios",
    precio: "$6000",
    id: 10,
    image: "https://via.placeholder.com/100",
  },
  {
    nombre: "canillera",
    categoria: "accesorios",
    precio: "$20000",
    id: 11,
    image: "https://via.placeholder.com/100",
  },
  {
    nombre: "MediasPremiun",
    categoria: "accesorios",
    precio: "$2500",
    id: 12,
    image: "https://via.placeholder.com/100",
  },
];
